### ISSUE TITLE
DatePicker textfield display dd-MMM-yy

### ISSUE THREAD

**Issue by kumarkrish85** [LGoodDatePicker/LGoodDatePicker#106]
Hi ,

How to modify the code/configure that display date picker text field in the format dd-MMM-yy (21-JUN-20)

thanks
Krishna

**Comment by devanand-sysvine** [comment]
There was a date picker settings which can be extended to change the format

**Comment by kumarkrish85** [comment]
> There was a date picker settings which can be extended to change the format

Yes, i can do it through date picker settings. Thanks
