### ISSUE TITLE
Toggle the month/year menus

### ISSUE THREAD

**Issue by ebourg** [LGoodDatePicker/LGoodDatePicker#110]
When I click accidentaly on the month or year of the CalendarPanel, a menu pops up and the only way to discard it is to click elsewhere. It would be nice to be able to click again the month/year to close the menu, just like clicking on the calendar button toggles the calendar popup.

**Comment by WiseEagleOwl** [comment]
@ebourg Thank you for reporting this issue. I have reproduced the problem and will look for a solution.

**Comment by WiseEagleOwl** [comment]
This issue was resolved in *LGoodDatePicker* version `v11.2.0`
