### ISSUE TITLE
How to set a limit for the years to show or pick?

### ISSUE THREAD

**Issue by Royercas** [LGoodDatePicker/LGoodDatePicker#114]
Hi!
I need to set a year range to show in order to pick a year. At maximum current year (2020) and as minimum 1950.

Also, is there any setting to allow user to scroll or navigate the years using the arrow keys ?
Currently I can't go beyond 2009 and it goes up to 2031

Thanks in advance

**Comment by WiseEagleOwl** [comment]
Hello @Royercas,
*LGoodDatePicker* only provides pickers for a date and/or time. If you are only interested in years than this component might not suit your purposes very well.
The year range shown in the year popup of the `CalendarPanel` is fixed to current year plus minus 11 years. You can enter a custom year by pressing the three dots `(...)` menu entry. Navigation via arrow keys is currently not supported.

To restrict the allowed date range you can implement a `DateVetoPolicy ` as used in the *demo* program:
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/8f227503c694a8f9be5a96314b5b37d7790c4f1c/Project/src/main/java/com/github/lgooddatepicker/demo/FullDemo.java#L1073-L1096

Feel free to leave a comment if this hasn't solved the issue for you.
