### ISSUE TITLE
Error when trying to add components to content pane using swing window builder

### ISSUE THREAD

**Issue by bbicudo** [LGoodDatePicker/LGoodDatePicker#129]
When i try to add components using windowbuilder i get the following errors:

![image](https://user-images.githubusercontent.com/22198380/112680958-cc3adb00-8e4c-11eb-9c3e-f720e5128377.png)

And

![image](https://user-images.githubusercontent.com/22198380/112681013-dceb5100-8e4c-11eb-9a18-31691bead596.png)

It may be something stupid, but i really don't know how to proceed. Can someone help?

**Comment by WiseEagleOwl** [comment]
@bbicudo I personally don't use *Eclipse* and cannot provide support regarding issues with its *WindowBuilder*. At first glance it seems like *LGoodDatePicker* is not on your *class path* and can therefore not be found.
A much better place to ask for guidance might be the [Eclipse WindowBuilder community forum](https://www.eclipse.org/forums/index.php/f/214/).

If you encounter any specific issue with our `DatePickerBeanInfo` or other `...BeanInfo` classes when using the *Eclipse WindowBuilder* feel free to comment on this issue.
