### ISSUE TITLE
Drop support for Java 6 and Java 7.

### ISSUE THREAD

**Issue by dbmalkovsky** [LGoodDatePicker/LGoodDatePicker#143]
It seems most projects have settled on JDK 8 as the oldest supported JDK level while many are looking at JDK 11 and later.   Why not drop the JDK 6 support for this project?

**Comment by BlakeTNC** [comment]
Supporting JDK 8 and above sounds fine by me. I imagine people could always use or fork the released [backport](https://github.com/LGoodDatePicker/LGoodDatePicker/releases/tag/Backports) versions if they desire JDK 6 or JDK 7 support. If you are interested in making this change in the main branch, then feel welcome. : )

**Comment by BlakeTNC** [comment]
Implemented in #144.
