### ISSUE TITLE
Reference a List of parents from a single DatePickerSettings (enhancement suggestion)

### ISSUE THREAD

**Issue by Gittino** [LGoodDatePicker/LGoodDatePicker#16]
Hi again Blake,
I have another enhancement suggestion.
It seems that the DatePickerSettings keep a reference to his parent DatePicker. It would be nice if instead of a single parent the DatePickerSettings would keep reference to a List of parents.
In this manner when an application is initialized a single DatePickerSettings is created with the desired style. Then all the date pickers are initialized with the same DatePickerSettings and share this common style without the need of create a DatePickerSettings with the same settings for each of them.
Thanks in any case.
Best regards.

**Comment by BlakeTNC** [comment]
Hello Gittino, Thank you for the idea. However, I think that implementing this change would be bad for the stability of the components. 

I would suggest the following procedure instead: If you'd like to conveniently create multiple date pickers with the same settings, you could put the code in a loop. If you have a requirement of modifying the settings of all those date pickers after creation, you could add the settings to an array of DatePickerSettings instances.

warm regards,
Blake
