### ISSUE TITLE
Bug report: Exception when setting a veto policy in a CalendarPanel.

### ISSUE THREAD

**Issue by willsuh** [LGoodDatePicker/LGoodDatePicker#17]
Hello,

I am using the latest version LGoodDatePicker 5.4.2.
I believe there is bug when setting veto policy for CalendarPanel.
The order is:
1. define DatePickerSettings;
2. define CalendarPanel with DatePickerSettings as input;
3. setVetoPolicy to the previously defined DatePickerSettings.

Error occurs:
java.lang.RuntimeException: DatePickerSettings.setVetoPolicy(), A veto policy can only be set after constructing the DatePicker.
at com.github.lgooddatepicker.datepicker.DatePickerSettings.setVetoPolicy(DatePickerSettings.java:845)

This error does not occur with DatePicker component.

My code:
DatePickerSettings settings = new DatePickerSettings();
settings.firstDayOfWeek = DayOfWeek.MONDAY;
settings.setAllowEmptyDates(false);
settings.highlightPolicy = new HighlightPeriod();
CalendarPanel customizedDatePicker = new CalendarPanel(settings);
settings.setVetoPolicy(new vetoPolicy());
customizedDatePicker.addCalendarSelectionListener(this);

One way to lure the procedure is the create an unused DatePicker (new DatePicker(settings)), just after defining the CalendarPanel.

Thank you to check this issue.
Guillaume

**Comment by BlakeTNC** [comment]
This is definitely a bug. Thank you for reporting this, I will fix it.
warm regards, 
Blake

**Comment by BlakeTNC** [comment]
Hello Guillaume,
This bug is now fixed, as of [LGoodDatePicker 7.1.1](https://github.com/LGoodDatePicker/LGoodDatePicker/releases). Please let me know if you find any other issues or if the bug fix does not work.

Warm regards,
Blake

**Comment by willsuh** [comment]
Hello Blake,
Thank you very much for this prompt update.

Regards,
Guillaume

**Comment by BlakeTNC** [comment]
Guillaume, No problem. It was a pretty major bug. I appreciate you telling me about it. I fixed it and made several other related changes so that other CalendarPanel settings will update properly if they are modified after the panel is constructed.

(Only if you like:) Will you add a "star" to LGoodDatePicker at the upper right corner of the [Main Page](https://github.com/LGoodDatePicker/LGoodDatePicker)? The stars help publicize the project. Thanks!

have a good day,
Blake

**Comment by BlakeTNC** [comment]
Guillaume, I ran a thorough test of the remaining independent CalendarPanel settings, and found 3 other settings (background color settings) that were not immediately updating if set after calling the independent CalendarPanel constructor. These settings are fixed, as of [LGoodDatePicker 7.1.2](https://github.com/LGoodDatePicker/LGoodDatePicker/releases). The 7.1.2 version is now also released on Maven Central. (It might take a few hours to update the Maven webpage though.) 

The independent CalendarPanel is the most recently added component in the library, but I think it's settings are likely more stable as of this release. (The CalendarPanel did exist in the library before, but previously only as a private component of the date picker.)

There's also an unrelated enhancement in the new version, related to how mouse clicks are interpreted. I thought I'd send you a quick note on these changes.
Blake

**Comment by willsuh** [comment]
Hello Blake,
Indeed, CalendarPanel component should be more stable in this release. Thank you for your mail.
By the way, may I suggest you a feature that could be implemented in a future release: the possibility to display the week of year (1 to 53) by the left side of the panel. Settings would consider to display or not such information, as well as setting the Locale parameter. This feature would be of great interest in my application.

Thank you and regards,
Guillaume

Envoyé de mon iPhone

**Comment by BlakeTNC** [comment]
To clarify: When you mentioned "setting the locale", are you talking about setting the locale after constructing the DatePickerSettings? You can currently change the locale when the settings are created (in the DatePickerSettings constructor). But it's a one-time thing at the moment, mostly because so many other settings would need to be changed any time the locale changed.

Warm regards,
Blake

**Comment by willsuh** [comment]
Hello Blake,
That is correct. Just to make sure that the Locale definition would also affect the week of year counting method.

Regards,
Guillaume

Envoyé de mon iPhone

**Comment by BlakeTNC** [comment]
Hi Guillaume, I've added your two feature requests as request #18 and #19. If you'd like to be notified of any future changes to those two issues, github does have a "subscribe" feature on each issue page. Thanks.

warm regards,
Blake

**Comment by BlakeTNC** [comment]
Hello, I thought I'd let you know that the week of the year feature has been added to the latest [Release](https://github.com/LGoodDatePicker/LGoodDatePicker/releases).
warm regards,
Blake

**Comment by willsuh** [comment]
Hello Blake,
Thank you for your mail. I have not checked your new release yet but I will give you my feedback soon.

Best regards,
Guillaume

Envoyé de mon iPhone

**Comment by BlakeTNC** [comment]
Hello Guillaume,
The ability to change the locale after constructing a DatePicker or independent CalendarPanel, (or to replace the entire DatePickerSettings instance if desired), has been implemented as of [LGoodDatePicker 7.3.1](https://github.com/LGoodDatePicker/LGoodDatePicker/releases). This completes feature request #18.

warm regards,
Blake
