### ISSUE TITLE
Ordering of options for DatePickerSettings

### ISSUE THREAD

**Issue by dbmalkovsky** [LGoodDatePicker/LGoodDatePicker#175]
If I use
<pre>
		dateSettings = new DatePickerSettings();
		dateSettings.setLocale(new Locale("fr"));
		dateSettings.setFormatForDatesCommonEra("dd/MM/yyyy");
</pre>
I see this (which is what I'd expect):
![image](https://user-images.githubusercontent.com/1105445/150005734-04f11b52-bdd7-4ed3-b65f-e7e53250d0c5.png)

If I move the `setLocale` after the `setFormatForDatesCommonEra` I see this (the yellow highlighting was added by me):
![image](https://user-images.githubusercontent.com/1105445/150006037-2919c8a9-567c-4be3-85aa-46f76b18a8eb.png)

Why does the code no longer respect the specified date formatting string?

**Comment by BlakeTNC** [comment]
This is expected behavior. here is the applicable javadoc with explanation.

```
  /**
   * setLocale, This will set the locale for this DatePickerSettings instance, and will set all
   * other settings that depend on the locale to their default values.
   *
   * <p>Warning: Every setting whose default value depends on the locale, will be overwritten
   * whenever this function is called.
   *
   * <p>This is a list of all the settings which are overwritten by this function: locale,
   * translationArrayStandaloneLongMonthNames, translationArrayStandaloneShortMonthNames,
   * translationToday, translationClear, formatForTodayButton, formatForDatesCommonEra,
   * formatForDatesBeforeCommonEra, formatsForParsing, firstDayOfWeek, weekNumberRules.
   *
   * <p>For most applications, it is generally recommended to only set the locale from the
   * DatePickerSettings constructor. If you use setLocale() to change the locale after construction,
   * then you will overwrite any previously customized locale-specific settings.
   *
   * <p>Passing in "null" will apply the default locale for the current Java Virtual Machine.
   */
  public void setLocale(Locale locale) {
```

**Comment by dbmalkovsky** [comment]
Sorry; my bad; didn't read far enough.

**Comment by BlakeTNC** [comment]
no problem. Cheers.
