### ISSUE TITLE
setselectesdate

### ISSUE THREAD

**Issue by oumaimasandbox** [LGoodDatePicker/LGoodDatePicker#176]
Hi,
is there anyway  to  do setSelectedDate  like we do in  for combobox (setselecteditem)? I really need for my project

**Comment by dbmalkovsky** [comment]
Are you looking for `setDate()`; see https://github.com/LGoodDatePicker/LGoodDatePicker/blob/7a9b61f2320fcf13f34aa5a16ba919ce00e162ec/Project/src/main/java/com/github/lgooddatepicker/components/DatePicker.java#L560

**Comment by oumaimasandbox** [comment]
SetDate();
doesnt work for datePicker if my variable is dateTime picker;

**Comment by dbmalkovsky** [comment]
have your tried `datetimePicker.datePicker.setDate()`?   `datePicker` is a public variable on the `DateTimePicker` object; see https://github.com/LGoodDatePicker/LGoodDatePicker/blob/7a9b61f2320fcf13f34aa5a16ba919ce00e162ec/Project/src/main/java/com/github/lgooddatepicker/components/DateTimePicker.java#L66

This is how I set date an time:
<pre>
        dateTimePicker.datePicker.setDate(dateTime.toLocalDate());
        dateTimePicker.timePicker.setTime(dateTime.toLocalTime());
</pre>

**Comment by BlakeTNC** [comment]
Closing this issue which is no longer active. Please comment if you need to reopen.
