### ISSUE TITLE
Year 0

### ISSUE THREAD

**Issue by Rexsur** [LGoodDatePicker/LGoodDatePicker#186]
If you go back enough you can see year 0 wich should't exist.

**Comment by BlakeTNC** [comment]
Hello, 
It looks like year zero is a legal year under the system used, which is ISO_8601. That is an international standard calendar system, and the java 8 date time api is based on that system. I hope that helps. 

See: https://en.wikipedia.org/wiki/ISO_8601#Years
Also: https://www.digitalocean.com/community/tutorials/java-8-date-localdate-localdatetime-instant
"The new Date Time API works on the ISO-8601 calendar system but we can use it with other non-ISO calendars as well."
