### ISSUE TITLE
Only showing legal/certain years in year selection popup

### ISSUE THREAD

**Issue by dosidw** [LGoodDatePicker/LGoodDatePicker#190]
Hi

My pull request had the solution to check if the year is legal if there is a `DateVetoPolicyMinimumMaximumDate`.

See: https://github.com/dosidw/LGoodDatePicker/commit/00a8b918489e77729b4ebedd6ecc368d384eda1a

You replied:
`..., but I lean against the idea of blocking vetoed years in the year popup. A veto policy is not supposed to affect navigation. Vetoing only happens when a user tries to select a specific date. This is intentional, since a veto policy could be as complex and fine grained as desired.`

I see 2 problems:

1) The user extends `DateVetoPolicyMinimumMaximumDate` to do something different instead of `DateVetoPolicy`.

2) We then have an asymmetry where the feature is missing for other `DateVetoPolicy` implementations and the user has no way of easily getting support for his class.

I think such a feature would be useful, so it would be nice if we can find a way you like too. E.g. if the date picker is for a date of birth, then allowing selecting the future does not make much sense.

I could live with problems 1) and 2) because `DateVetoPolicyMinimumMaximumDate` is the only implementation the framework provides, so all internal policies are supported. And I assume having a simple start/end date policy is what 90% or more of cases need. So this implementation is very simple and probably handles 90+% of cases.

Or should I try to design a different solution? E.g. `DatePickerSettings.yearSelectionValidRange` and with an interface with same method names as `DateVetoPolicyMinimumMaximumDate`, so have that class implement that interface? It is almost the same, with an indirection more. But then user has to add his policy to settings, so the feature is opt-in. And the user could also implement custom `YearSelectionValidRange` for his custom policy, so it is partly a solution for problem 2).

Kind regards
Dirk

**Comment by dosidw** [comment]
Better version:
https://github.com/dosidw/LGoodDatePicker/commit/4fa939b53d3970ec0eb5eab5c1addb74107d3635

There is `DatePickerSettings.getDateRangeLimits()`. So I now use that. It does what I did above for us: for `DateVetoPolicyMinimumMaximumDate` it gets the interval, otherwise start/end is null.

But the user can that method, so 2) is partly solved.

So this variant is basically identical to the second approach above, except that is always active at the moment, and not just opt-in like the one above.

**Comment by BlakeTNC** [comment]
I committed your previous pull request (https://github.com/LGoodDatePicker/LGoodDatePicker/pull/189), with some modifications that you will likely want to review.

Yes, I could support these ideas. 
The usage of DatePickerSettings.getDateRangeLimits() seems like a good thing.
And it seems good to make it universal (instead of optional) when DateVetoPolicyMinimumMaximumDate is used. 
I haven't looked into these things very closely. So use your judgment with all implementation choices, including the details mentioned in this paragraph.

I will review your pull request when and if submitted. Thank you

**Comment by dosidw** [comment]
Ok, thanks a lot. I created PR 191.

Note: I created a local build for us until you create a new release. I had to go back to `packing=jar` from `packing=bundle`, because of classes missing in the .jar (e.g. `Preconditions` class was missing).
