### ISSUE TITLE
dynamically trigger update of DateHighlightPolicy

### ISSUE THREAD

**Issue by willsuh** [LGoodDatePicker/LGoodDatePicker#23]
Hello,
I am using package version 7.2.3.
I am encountering issue when trying to dynamically update `DateHighlightPolicy` of `CalendarPanel`.
Some parts of my code:
`CalendarPanel picker = new CalendarPanel(...);`
`picker.addCalendarSelectionListener(this);`
The enclosing class implements `CalendarSelectionListener`:
`...`
`@Override`
`    public void selectionChanged(CalendarSelectionEvent event) {`
`        selectedDate = event.getNewDate();`
`}`
LocalDate `selectedDate`, defined on top of that, is a parameter of a class implementing DateHighlightPolicy :
`private class HighlightPeriod implements DateHighlightPolicy {`
`             @Override`
`             public HighlightInformation getHighlightInformationOrNull(LocalDate ld) {`
`               if ((ld.isAfter(LocalDate.now()) || ld.isEqual(LocalDate.now()))`
`              && (ld.isBefore(selectedDate) || ld.isEqual(selectedDate))) {`
`              return new HighlightInformation(Color.GREEN,Color.BLACK,"selected period");`
`           }`
`          return null;`
`      }`
`}`
`HighlightPeriod` does not updated according to `selectedDate` change. I have to click twice on a date for the `DateHighlightPolicy` to update.

Thank you for your feedback.
Will

**Comment by BlakeTNC** [comment]
Hello Will,
Can you supply a complete minimal example that demonstrates the bug that you want to fix? (Something small and executable that I can debug.) A zipped minimal example project, or self-contained executable class could work.

warm regards,
Blake

**Comment by BlakeTNC** [comment]
PS, you would want to update to the latest version while exploring this bug. Especially because there were major structural changes in 7.3.1.

**Comment by willsuh** [comment]
Hello Blake,
 
I have updated to the latest release. Still encountering the same issue.
Enclosed is a minimal example demonstrating this issue.
Thank you.
 
Regards,
Will
 
Date: Thu, 16 Jun 2016 01:58:30 -0700

**Comment by BlakeTNC** [comment]
Your attachment was not included. Maybe try attaching it using the github issue web interface?
at the bottom of the reply form, I see this text: "Attach files by dragging & dropping, selecting them, or pasting from the clipboard."
-Blake

**Comment by willsuh** [comment]
Hello,
Please check enclosed file.
[testUpdateHighlight.java.zip](https://github.com/LGoodDatePicker/LGoodDatePicker/files/321535/testUpdateHighlight.java.zip)

**Comment by BlakeTNC** [comment]
This bug was fixed as of [LGoodDatePicker 7.4.3](https://github.com/LGoodDatePicker/LGoodDatePicker/releases).

Note: A cleaned up version of the code that was used to test this bug, is included in release 7.4.3 as the following class: "com.github.lgooddatepicker.ysandbox.TestUpdateHighlightPolicy".

Thanks, Will, for reporting this bug.
-Blake
