### ISSUE TITLE
Feature request: Disable month and year popup menus (but still display the Month and Year)

### ISSUE THREAD

**Issue by willsuh** [LGoodDatePicker/LGoodDatePicker#24]
Hello,
Following feature request #22 recently implemented in the latest release, I would propose another improvement:
Ability to disable buttons (Month and Year), but still having the information of the Month and Year corresponding to the current view.
Enabled mode: the current situation (implementing JComboBox)
Disabled mode: display Month and Year in JLabel instead.

Thank you for considering this improvement.
Will

**Comment by BlakeTNC** [comment]
I can see how this feature would be useful. Keeping this feature request, thanks.
-Blake

**Comment by BlakeTNC** [comment]
This feature was implemented as of [LGoodDatePicker 7.4.2](https://github.com/LGoodDatePicker/LGoodDatePicker/releases)
