### ISSUE TITLE
Feature request: New settings for TimePicker text field background color

### ISSUE THREAD

**Issue by b0rt3d** [LGoodDatePicker/LGoodDatePicker#25]
Add the ability to change the colors for the time picker text field.

**The following settings and functions would be added to the TimePickerSettings class:**

New TimePickerSettings Area enums (with the default values):
TimePickerTextValidTime(Color.black),
TimePickerTextInvalidTime(Color.black),
TimePickerTextVetoedTime(Color.black),

TimePickerTextFieldBackgroundValidTime(Color.white),
TimePickerTextFieldBackgroundInvalidTime(Color.white),
TimePickerTextFieldBackgroundVetoedTime(Color.white),
TimePickerTextFieldBackgroundDisallowedEmptyTime(Color.pink),

New TimePickerSettings functions:
setColor (Area area, Color color){}
getColor(){}

**Comment by b0rt3d** [comment]
So...
I added the enum Area to TimePickerSettings with those 7 entries,
the field HashMap colors,
the method Color getColor()
and now for the method setColor (Area area, Color color) I don't really know what to do with each area case.

Will investigate further later, cheers,
Albert

**Comment by BlakeTNC** [comment]
Hello Albert,
   Most of the usages for these colors is going to be in the following function:
TimePicker.zDrawTextFieldIndicators()
The same function in the DatePicker can provide an example of implementation. 

setColor doesn't have to do much. It does not even need a switch statement, it just essentially needs the default section from the same setColor function in the date picker settings.

                if (parent != null) {
                    parent.zDrawTextFieldIndicators();
                }

If you use NetBeans you can right-click on the pre-existing color variables (like TimePickerSettings.colorTextValidTime) in time picker settings to find all the usages of each variable "find usages". I'm sure that eclipse has a similar option. The new code will be replacing those three variables. Each usage of the existing variables will need to be replaced with code for accessing the matching color from the hashmap.

You have already done most of the work of implementing this feature, I'd be fine with doing the rest if desired, or you working on it. I noticed that you did not fork the repository yet, so I can't see your work so far. To fork the repository, you would click the fork button in the upper right corner of the main LGoodDatePicker page, which would instantly copy the repository to your github account. To modify the repository or commit your work you would download github desktop and learn it's basic features
(clone, commit, and sync). https://desktop.github.com/ If you do commit and sync after each day's work, it would be easier to give you comments or help on how it's going so far.

Something called a "github pull request" is used when you are ready to request merging your work back to the main repository. It's all at least a little simpler than it sounds.

All the basics of that stuff are in the github desktop user guides here:
https://help.github.com/desktop/guides/

good work so far.
-Blake

**Comment by BlakeTNC** [comment]
ps, I see now that you already did fork the repo, (it just wastn't showing up in the fork list yet). -Blake

**Comment by b0rt3d** [comment]
I think I did all the changes needed for it to work. 
I tested building it and running the Demos and all worked fine.

Also had to replace one occurrence of the old field TimePickerSettings.colorValidText in BasicDemo.java to use the new setColor method.

Deleted these 3 old Color fields that were no longer used.

I made a pull request for you to check the changes, but not sure if I forked your project properly so I'll just wait for you to tell me what to do.

By the way, thanks for letting me help you here, I'm learning a lot already :smile: 

Have a great day Blake,
Albert.

**Comment by b0rt3d** [comment]
Oh, I also removed the "private" tag from TimePicker's method:
**void zDrawTextFieldIndicators()**
Since it was being called from the settings' class and I also saw the same function being public in DatePicker.java

**Comment by BlakeTNC** [comment]
hi Albert,
It's looking great so far. And you're welcome, thanks for your interest in improving the project.

When I looked at the list of changes, I found the following minor issues that could use fixing:

- The default color for TimePickerTextInvalidTime should be Color.red.
- In TimePicker.java, you should import the Area enum so that you don't have to fully qualify every area name. (Then remove the "TimePickerSettings" prefix from all the Area usages.)
Something like this: import com.github.lgooddatepicker.components.TimePickerSettings.Area; See how the Areas are referenced in the DatePicker.java for an example. 
- The above change should also be made in BasicDemo.java.
- The TimePickerSettings.Area enum needs a javadoc comment. See DatePickerSettings.Area for an example comment.
- To make the names a little shorter, I'm thinking we should rename all the background areas from "TimePickerTextFieldBackground" to "TextFieldBackground". (And should do the same thing for all the text field backgrounds in the date picker as well.) We could leave the text (foreground) color areas the way they are.

warm regards,
Blake

**Comment by BlakeTNC** [comment]
PS, I -think- that any new commits you make can (or will?) automatically be added to the pull request. I don't think you have to remake the pull request... I suppose there might or might not be a button for "updating" the pull request afterwards, I'm not sure.

**Comment by BlakeTNC** [comment]
PPS, So that people can use both enums at once in the same class (both unqualified), I am thinking we should make the enum names unique... perhaps "DateArea" and "TimeArea" would work. (unless either one of us thinks of something better).

**Comment by b0rt3d** [comment]
Hi Blake,

I made all the changes you proposed, if you see anything, just tell.

Glad to be of help :smile: 
Best regards,
Albert

**Comment by BlakeTNC** [comment]
Hi Albert, 
Nice work. 
I did a bit of testing and it looks like it's working properly. I've merged the pull request, updated the project version number, and published a new release with your changes. The code looks great. Thanks for implementing this feature.
-Blake

**Comment by BlakeTNC** [comment]
**This feature was implemented as of [LGoodDatePicker 7.4.4](https://github.com/LGoodDatePicker/LGoodDatePicker/releases)**
