### ISSUE TITLE
How to Install It to Eclipse?

### ISSUE THREAD

**Issue by BerkerD** [LGoodDatePicker/LGoodDatePicker#27]
Hello, can you tell me how can i implement this to my java code? I cannot see any instructions for that.
Thank you in advance,

**Comment by BlakeTNC** [comment]
Hello,
Here are some basic instructions for installing and using the LGoodDatePicker library in Eclipse.

1) You can download the latest LGoodDatePicker release at the [Release Page](https://github.com/LGoodDatePicker/LGoodDatePicker/releases). The most important file you will need is named "LGoodDatePicker-(version number).jar"
2) You will need to create (or already have created) a Java project in Eclipse. 
3) You can install any library that is packaged as a jar (including LGoodDatePicker) into your project, by following the instructions and screenshots on this page: [How to import a Jar in Eclipse - StackOverflow](http://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse)
4) To get started adding pickers to your project, see the source code in the [LGoodDatePicker Demo Folder](https://github.com/LGoodDatePicker/LGoodDatePicker/tree/master/Project/src/main/java/com/github/lgooddatepicker/demo). The simplest demo is called "[BasicDemo.java](https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/demo/BasicDemo.java)".

warm regards,
Blake
