### ISSUE TITLE
future request: add min/max limit of date to select

### ISSUE THREAD

**Issue by mcwolfmm** [LGoodDatePicker/LGoodDatePicker#36]
I'm looking for the ability to set start and end date. It would be great if you add an option for setting the minimum and / or maximum date that can be selected.

**Comment by BlakeTNC** [comment]
Hello,
This functionality does exist, through using a DateVetoPolicy. To implement this, you would create a veto policy that vetoes any date outside of your chosen date range. Then you can add the veto policy to the date picker using DatePickerSettings.setVetoPolicy().

See the Javadocs for DateVetoPolicy.java. Also see the veto policy example located in FullDemo.java. In the full demo, search for the text "SampleDateVetoPolicy" and "Create a date picker: With veto policy."

Links to source of the the relevant files are pasted below.

warm regards,
BlakeTNC

https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/optionalusertools/DateVetoPolicy.java

https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/demo/FullDemo.java

**Comment by mcwolfmm** [comment]
10x for support.
Work fine.

**Comment by BlakeTNC** [comment]
Issue follow-up:  Apparently, other developers are also having trouble finding this functionality when they need it. For this reason, I've created a new feature request to add a convenience function for setting a limit on the minimum and maximum date picker dates. The function would create a veto policy for the purpose. (Issue #44)

**Comment by BlakeTNC** [comment]
Issue #44 has been implemented as of [LGoodDatePicker 8.2.1](https://github.com/LGoodDatePicker/LGoodDatePicker/releases).

An example for using the new feature has been added to the full demo. The new (full demo) source code for implementing the desired functionality looks like this:

        // Create a date picker: With date range limits.
        // Notes: 
        // * If you only want to limit one side of the date range, you can optionally pass in null 
        // for one of the date limits.
        // * Date range limits (and other types of veto policies) can only be set after constructing 
        // the date picker.
        dateSettings = new DatePickerSettings();
        datePicker = new DatePicker(dateSettings);
        LocalDate today = LocalDate.now();
        dateSettings.setDateRangeLimits(today.minusDays(20), today.plusDays(20));
        panel.panel1.add(datePicker, getConstraints(1, (row * rowMultiplier), 1));
        panel.addLabel(panel.panel1, 1, (row++ * rowMultiplier), 
                "Date 5, Limit date range (+/- 20 days):");
