### ISSUE TITLE
Would like option to pass data ranges for controled input purposes.

### ISSUE THREAD

**Issue by Sarge555** [LGoodDatePicker/LGoodDatePicker#42]
I don't see this option for this so forgive me if I missed it.
It would be cool to limit the range of the calendar within the calendar itself. Example : If I can't buy tickets more than 3 months from current day, I would like the calendar to not show dates past that range or prior to today. Months that have some active dates would show with disabled days for dates outside the range - and no ability to show months or years past the range.

**Comment by BlakeTNC** [comment]
Hello,
This functionality does exist, through using a DateVetoPolicy. To implement this, you would create a veto policy that vetoes any date outside of your chosen date range. Then you can add the veto policy to the date picker using DatePickerSettings.setVetoPolicy().

See the Javadocs for DateVetoPolicy.java. Also see the veto policy example located in FullDemo.java. In the full demo, search for the text "SampleDateVetoPolicy" and "Create a date picker: With veto policy."

Links to source of the the relevant files are pasted below.

warm regards,
BlakeTNC

https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/optionalusertools/DateVetoPolicy.java

https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/demo/FullDemo.java

**Comment by BlakeTNC** [comment]
PS, You are not the first developer to have trouble finding this functionality when you needed it. For this reason, I've created a new feature request to add a convenience function for the purpose. (Issue #44)

**Comment by BlakeTNC** [comment]
Issue #44 has been implemented as of [LGoodDatePicker 8.2.1](https://github.com/LGoodDatePicker/LGoodDatePicker/releases).

An example for using the new feature has been added to the full demo. The new (full demo) source code for implementing the desired functionality looks like this:

        // Create a date picker: With date range limits.
        // Notes: 
        // * If you only want to limit one side of the date range, you can optionally pass in null 
        // for one of the date limits.
        // * Date range limits (and other types of veto policies) can only be set after constructing 
        // the date picker.
        dateSettings = new DatePickerSettings();
        datePicker = new DatePicker(dateSettings);
        LocalDate today = LocalDate.now();
        dateSettings.setDateRangeLimits(today.minusDays(20), today.plusDays(20));
        panel.panel1.add(datePicker, getConstraints(1, (row * rowMultiplier), 1));
        panel.addLabel(panel.panel1, 1, (row++ * rowMultiplier), 
                "Date 5, Limit date range (+/- 20 days):");

**Comment by Sarge555** [comment]
Blake,
           This is a much better implementation.  Thank you!
My only other recommendation regarding this is it would be nice it the months outside the range were not reachable. If the << . <. >,>> buttons did no allow you to view a month that was outside the range it would force users to accept their options instead of looking where there are no options.
Just a thought. Thank you for the excellent work.
Keith
