### ISSUE TITLE
Settting the icon for the dateEdit.getDatePicker().getComponentToggleCalendarButton() only shows when selected

### ISSUE THREAD

**Issue by Sarge555** [LGoodDatePicker/LGoodDatePicker#43]
When setting the icon for the ToggleCalendarButton, the icon only shows when pressed - would like it to always show.
Drilling down into the components and setting the several other *Icon related methods did not change the behaviour.

Is there another way to set the icon?

**Comment by BlakeTNC** [comment]
Hello, The full demo ( FullDemo.java ) includes a working example of how to set the icon on the date picker toggle calendar button.

Pasted below is the source code from that section of the demo. Of course, you will have to modify it to meet your specific needs and programmatic environment. 

If your icon is only showing when you press it down, perhaps you used the function called "setPressedIcon"? I don't know, that is just a guess. Please let me know if you have any other needs.

warm regards,
Blake

        // Create a date picker: Custom button icon.
        // You can replace the example image with any image file that is desired.
        // See also: JButton.setPressedIcon() and JButton.setDisabledIcon().
        // Get the example image icon.
        URL dateImageURL = FullDemo.class.getResource("/images/datepickerbutton1.png");
        Image dateExampleImage = Toolkit.getDefaultToolkit().getImage(dateImageURL);
        ImageIcon dateExampleIcon = new ImageIcon(dateExampleImage);
        // Create the date picker, and apply the image icon.
        dateSettings = new DatePickerSettings();
        datePicker = new DatePicker(dateSettings);
        datePicker.setDateToToday();
        JButton datePickerButton = datePicker.getComponentToggleCalendarButton();
        datePickerButton.setText("");
        datePickerButton.setIcon(dateExampleIcon);
        panel.panel1.add(datePicker, getConstraints(1, (row * rowMultiplier), 1));
        panel.addLabel(panel.panel1, 1, (row++ * rowMultiplier), "Date 7, Custom Icon:");

**Comment by Sarge555** [comment]
Blake, 

          I wanted to make sure I was doing this correctly before I bothered you about this, but am still having the same issue in the JTable using the latest 8.2.2 build.  I apologize for not getting back sooner.  Basically, it only shows the icon or button text changes when the date column is selected but no other time.

I don't believe the panel related code applies but I may be wrong. Please advise.

I've added lines 91-101 to the TableDemo.  Please see and run the attachment.
Thanks!
Keith

**Comment by BlakeTNC** [comment]
Hello, FYI, I don't see any attachments in your message.
Now that I know you are using JTable, that makes a big difference in me understanding what is probably happening in your code.  

The DateTableEditor class says this at the top of its Java docs:

"This class can be used as a table cell "Editor", or as a "Renderer", or as both editor and renderer. Separate class instances should be used for the editor and the renderer."

If you are only seeing your changes when you select a cell, that likely means that you have changed the look of your table editor instance, but not your table renderer instance. You will need to change the look of both instances, if you want to see your changes at all times.

Table editors and renders are not simple topics, but you can read some about them here:
http://docs.oracle.com/javase/tutorial/uiswing/components/table.html#editrender

In the demo, look for the lines that look like this:

        table.setDefaultRenderer(LocalDate.class, new DateTableEditor());
        DateTableEditor dateEdit = new DateTableEditor();
        dateEdit.clickCountToEdit = clickCountToEdit;
        table.setDefaultEditor(LocalDate.class, dateEdit);

You will need to customize each of the two (2) "new DateTableEditor()" instances before passing them into the table as editor or renderer. 

Hopefully, this help will point you in the right direction. 
warm regards, 
Blake

**Comment by Sarge555** [comment]
That is the solution. Thanks!
Keith

**Comment by BlakeTNC** [comment]
Yay I'm glad it worked. 
Cheers,
Blake
