### ISSUE TITLE
Can't parse Time Picker to 24 hour format.

### ISSUE THREAD

**Issue by heyJar** [LGoodDatePicker/LGoodDatePicker#48]
I am using this library to pick time, my problem is I can't parse it to 24 hour format since I want it to be inserted to my database. 

java.text.ParseException: Unparseable date: "10:30pm"
The acceptable format is "10:30 pm" with space to be converted to 22:30.
Can you help me with this? Or any other way to solve my problem. Thanks

**Comment by BlakeTNC** [comment]
Hi, 
As I understand, you are using the time picker to pick a time, and you need to convert the chosen time to a specific format for your database. Is this correct?

It sounds like you are retrieving the time as a text string. 
Instead, I would suggest calling the function in the TimePicker class called:
public LocalTime getTime().

This will return a LocalTime object, which you can then format to any desired text format. 
To format a LocalTime object, you would call LocalTime.format(yourFormatterHere);

warm regards,
Blake

**Comment by BlakeTNC** [comment]
See also: https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html#format-java.time.format.DateTimeFormatter-

**Comment by BlakeTNC** [comment]
Please let me know if this solves your problem. Also, if you like please add a star to the top of the [project page](https://github.com/LGoodDatePicker/LGoodDatePicker) on github. Thanks!
-Blake

**Comment by heyJar** [comment]
I already solved my problem, thank you! Starred. I have a question, can I set the time to 24 hour format and remove AM/PM to your Time picker? Thanks

**Comment by BlakeTNC** [comment]
Hello, Sure, setting the format is easy enough. You would want to look for the functions in TimePickerSettings called setFormatForDisplayTime() and setFormatForMenuTimes(). The simplest overloaded version of those functions would probably be the ones that accept a pattern string.

Use any pattern found here: https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

The pattern string you are looking for is probably something like "HH:mm".

In general,  you probably want to skim through the functions that are available in DatePickerSettings, and TimePickerSettings, to familiarize yourself with them. Pretty much any customizations you want to make to the components can be found in those two classes.

Warm regards,
Blake

**Comment by heyJar** [comment]
I am having hard time figuring out how to set the settings since I am still learning java. Can you do it for me? Example I have this variable of TimePicker called monAMStart. Thank you so much

**Comment by BlakeTNC** [comment]
Hello, 
You can get a basic example from this file:
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/demo/BasicDemo.java

Specifically this section:
        // Create a time picker with some custom settings.
        TimePickerSettings timeSettings = new TimePickerSettings();
        timeSettings.setColor(TimeArea.TimePickerTextValidTime, Color.blue);
        timeSettings.initialTime = LocalTime.now();
        TimePicker timePicker2 = new TimePicker(timeSettings);
-Blake

**Comment by BlakeTNC** [comment]
PS, I can't write the code for you, I can only point to learning resources if needed. It is important to learn some java basics to use a GUI component like this. Congratulations on trying to learn Java! :)
