### ISSUE TITLE
Rendering issue with substance

### ISSUE THREAD

**Issue by nroduit** [LGoodDatePicker/LGoodDatePicker#51]
Even with the settings, it seems not possible to render correctly some components with [substance](https://github.com/kirill-grouchnikov/substance). 

With default settings:
![screenshot-default](https://cloud.githubusercontent.com/assets/993975/25306419/1d7a936e-278d-11e7-93ed-8b0c13c24a2b.png)

Best after playing with settings:
![screenshot-settings](https://cloud.githubusercontent.com/assets/993975/25306466/e7a6fa2e-278d-11e7-9b36-c01fed1f586a.png)

**Comment by BlakeTNC** [comment]
Hello,
Pasted below are all the "color areas" of the date picker that can currently be changed (from DatePickerSettings.java). I'm not sure whether or not this provides complete coverage of the calendar panel, for total control of the coloring scheme (or not). (I've never checked to see if every portion of the components allows for manual color changing.) 

Pull requests are welcome. If there are some colors that cannot currently be changed, it would be possible for a person with the prerequisite programming skills and motivation to add those settings. They would need to add their needed color setting options to the DatePickerSettings file and associated rendering sections, and submit a pull request with those modifications. I would provide support if there were any questions about the existing code during that development process.
warm regards,
Blake

- Start of pasted code-
    /**
     * DateArea, These enumerations represent areas of the components whose color can be changed.
     * These values are used with the setColor() function, to set the color of various areas of the
     * DatePicker or the CalendarPanel. The default color for each area is also defined here.
     *
     * Note: A default color of "null" means that the default color for that element is supplied by
     * the swing component. The default color for "BackgroundMonthAndYearNavigationButtons" is null,
     * so those buttons will use the default background color supplied by the JButton class.
     */
    public enum DateArea {
        BackgroundClearButton(new Color(240, 240, 240)),
        BackgroundMonthAndYearMenuButtons(new Color(240, 240, 240)),
        BackgroundMonthAndYearNavigationButtons(null),
        BackgroundOverallCalendarPanel(new Color(240, 240, 240)),
        BackgroundTodayButton(new Color(240, 240, 240)),
        BackgroundTopLeftLabelAboveWeekNumbers(new Color(184, 207, 229)),
        CalendarDefaultBackgroundHighlightedDates(Color.green),
        CalendarBackgroundVetoedDates(Color.lightGray),
        TextFieldBackgroundDisallowedEmptyDate(Color.pink),
        TextFieldBackgroundInvalidDate(Color.white),
        TextFieldBackgroundValidDate(Color.white),
        TextFieldBackgroundVetoedDate(Color.white),
        DatePickerTextInvalidDate(Color.red),
        DatePickerTextValidDate(Color.black),
        DatePickerTextVetoedDate(Color.black);

        DateArea(Color defaultColor) {
            this.defaultColor = defaultColor;
        }
        public Color defaultColor;
    }
- End of pasted code-

**Comment by BlakeTNC** [comment]
ps, See also, the "color change" entry in the full demo. I think it changes one or two colors that you did not change in your screenshot:

        // Create a date picker: Change Colors.
        dateSettings = new DatePickerSettings();
        dateSettings.setColor(DateArea.BackgroundOverallCalendarPanel, Color.green);
        dateSettings.setColorBackgroundWeekdayLabels(Color.orange, true);
        dateSettings.setColor(DateArea.BackgroundMonthAndYearMenuButtons, Color.yellow);
        dateSettings.setColor(DateArea.BackgroundTodayButton, Color.yellow);
        dateSettings.setColor(DateArea.BackgroundClearButton, Color.yellow);
        dateSettings.setColor(DateArea.BackgroundMonthAndYearNavigationButtons, Color.cyan);
        datePicker = new DatePicker(dateSettings);
        panel.panel1.add(datePicker, getConstraints(1, (row * rowMultiplier), 1));
        panel.addLabel(panel.panel1, 1, (row++ * rowMultiplier), "Date 9, Change Colors:");

**Comment by nroduit** [comment]
Thanks for your suggestions but it only allow to change the header of the table.

I will try to make a pull request.

**Comment by BlakeTNC** [comment]
Hello @nroduit,
I have just now implemented and released the ability to change every visible color and every visible font. Please see [LGoodDatePicker 10.2.3](https://github.com/LGoodDatePicker/LGoodDatePicker/releases).

This should fully solve the issue you have shown here. Please let me know if everything is working for you.

Warm regards,
Blake

**Comment by nroduit** [comment]
Thanks for this new release. Yes it is now possible to use substance and configure colors to have enough contrast between text, background and highlight.
I haven't found where to configure the blue rollover color and some color properties have no effect (like CalendarDefaultTextHighlightedDates and CalendarDefaultBackgroundHighlightedDates). This could be due to Substance which overrides some rollover colors.

An improvement would be to remove default hard coded color and use instead colors related to L&F like the followings examples:
UIManager.getColor("controlHighlight");
UIManager.getColor("Panel.background");

**Comment by BlakeTNC** [comment]
Hello,
Just a quick note: "CalendarDefaultTextHighlightedDates and CalendarDefaultBackgroundHighlightedDates" will only appear if there is a "DateHighlightPolicy" instance set on the date picker. The same goes for any "Veto" related colors (they need a DateVetoPolicy to have any effect). 
warm regards,
Blake
