### ISSUE TITLE
Nimbus toggle button formatting for Time and Date pickers

### ISSUE THREAD

**Issue by Orbiter00** [LGoodDatePicker/LGoodDatePicker#52]
When using Nimbus L&F, the menu toggle button cause the height of the test field to grow.  Adding the margin and border as from the text field changes this behavior.

        toggleCalendarButton.setMargin(new Insets(1, 3, 2, 2));
        toggleCalendarButton.setBorder(new CompoundBorder(
                new MatteBorder(1, 1, 1, 1, new Color(122, 138, 153)),
                new EmptyBorder(1, 3, 2, 2)));

**Comment by BlakeTNC** [comment]
I was not able to reproduce this. Can you provide example code that demonstrates the problem?
Thank you.
Blake
