### ISSUE TITLE
Feature Request: Add colors for selected date to customizable colors.

### ISSUE THREAD

**Issue by ArchieBlack** [LGoodDatePicker/LGoodDatePicker#55]
CalendarPanel (around line 744) defines hard coded colors for the selected date.  It would be nice to be able to set that color like the others.

**Comment by BlakeTNC** [comment]
This feature has been implemented and committed to the master branch as of LGoodDatePicker 10.2.5-BETA. Thanks to @ArchieBlack for developing the enhancement. 
-Blake

**Comment by BlakeTNC** [comment]
LGoodDatePicker 10.3.1 has been released with these features. This release is available in the [Release Section]( https://github.com/LGoodDatePicker/LGoodDatePicker/releases), on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7CLGoodDatePicker), and as an [LGoodDatePicker Backport](https://github.com/LGoodDatePicker/LGoodDatePicker/releases/tag/Backports).
-Blake
