### ISSUE TITLE
DateTimePicker leaves grey box

### ISSUE THREAD

**Issue by hdstusnick** [LGoodDatePicker/LGoodDatePicker#59]
After clicking on the ... button to the right of the field, a grey box shows up where the calendar should be. Once the ... is clicked again, the calendar appears. However, the main problem is that once a date is selected or when the ... is clicked, the calendar leaves behind a grey box which exists in place throughout all the tabs of the application.

**Comment by BlakeTNC** [comment]
Note: The issue creator closed this issue without comment. The problem is assumed to be resolved. 
-Blake
