### ISSUE TITLE
Calendar Panel showing faulty days and order of days

### ISSUE THREAD

**Issue by msnijd** [LGoodDatePicker/LGoodDatePicker#61]
Hello,

First of all my compliments for this great date picker control.
However when I browse to previous or next months or years a bit quickly, sometimes the control shows the dates of the calendar month in the wrong order. Also sometimes double days appear, like in the attached screenshot for day number 31.
It seems to only happen when you browse fast.

My DateHighlightPolicy has to do some work (database queries, calculations etc), which takes up some processing time, so this is maybe why I get this behavior when I browse fast through the months. 

Than, when I move the mouse over the month-name label or over the Today button, the panel repaints itself and is OK ( day colouring as expected) again.

Thanks,
Max

For example :
![screen shot 2017-10-20 at 11 21 20](https://user-images.githubusercontent.com/32948262/31803996-5ab2582c-b589-11e7-99d6-ab8201f146bb.png)

**Comment by msnijd** [comment]
The program below demonstrates the problem. Just browse a few times quickly forth and back over the green and red blocked calender months using the '< ' and '>' buttons, and you will see anomalies.
When ever the mouse is moved over the Month or Today label the component renders itself again and shows a expected calendar month.

By the way my platform is MacOSX, I am using Java 1.8.0_144.

Try this code :

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;

import javax.swing.JFrame;
import javax.swing.JPanel;

import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.optionalusertools.DateHighlightPolicy;
import com.github.lgooddatepicker.optionalusertools.DateVetoPolicy;
import com.github.lgooddatepicker.zinternaltools.HighlightInformation;


public class DatePickerTest {

	public static void main(String[] args) {
		
		
		DatePickerSettings datePickerSettings = new DatePickerSettings();
		datePickerSettings.setAllowKeyboardEditing(false);
		datePickerSettings.setWeekNumbersDisplayed(true, true);
		datePickerSettings.setHighlightPolicy(new DailyTableHighLightPolicy());
		datePickerSettings.setVisibleClearButton(false);		
		DatePicker datePicker = new DatePicker(datePickerSettings);
		datePickerSettings.setVetoPolicy(new MyDateVetoPolicy());

		JFrame frame = new JFrame("TEST");
	    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	    JPanel p = new JPanel();
	    p.add(datePicker);
	    frame.add(p, BorderLayout.NORTH);
	    frame.setSize(400, 150);
	    frame.setVisible(true);
	}
	
	private static class MyDateVetoPolicy implements DateVetoPolicy {

		@Override
		// Only allowed within period [now - 100days, to now + 100days]
		public boolean isDateAllowed(LocalDate date) {
			System.out.println("Checking allowed: " + date.toString());
			
			LocalDate now = LocalDate.now();
			if (date.isBefore(now.minusDays(100))) {
				return false;
			}			
			else if (date.isAfter(now.plusDays(100))) {
				return false;
			}
			else {
				return true;
			}
		}
    }
	
	private static class DailyTableHighLightPolicy implements DateHighlightPolicy {

		@Override
		// days should be painted red and green, in a chess board style
		public HighlightInformation getHighlightInformationOrNull(LocalDate date) {
			System.out.println("Checking status: " + date.toString());
			
			// On even day numbers it is red, otherwise green
			int remainder =  date.getDayOfMonth() % 2;

			if (remainder == 0) {
				return new HighlightInformation(Color.red, null, "red");
			}
			else {
				return new HighlightInformation(Color.green, null, "green");
		    }
		}
	}
}

**Comment by msnijd** [comment]
![screen shot 2017-10-29 at 14 58 47](https://user-images.githubusercontent.com/32948262/32141380-b0b2566e-bcb9-11e7-945d-0a04bca79e85.png)

**Comment by msnijd** [comment]
Meanwhile I have fixed the issue myself with a workaround.

**Comment by msnijd** [comment]
No feedback on the issue yet. This datepicker doesn't seem to be very alive.

**Comment by BlakeTNC** [comment]
Hello Max, 
My apologies for the lack of response. I ran  your example code and I could not duplicate the issue for myself, and therefore could not troubleshoot it. Though it should be noted that I am running on Windows, and it's possible that the issue may only appear on Mac OS X. 

I have not had much time to perform new work for the date picker, though thankfully it has not seemed to need much work. The project is in wide use and receives infrequent bug reports.

Open source projects rely on users and multiple developers for extended usefulness. You mentioned fixing the problem with a workaround. Pull requests for the project are welcome. If you are able to develop a fix, you could create a pull request. 

Warm regards,
Blake

**Comment by msnijd** [comment]
Hello Blake,

Thank you for your reaction.
My apologies for the late answer, I have been very busy in the last days,
and could not the time to answer your email.
That is why also I will not have any time to look into your sources and try
to fix the issue any day soon.

I think I would agree to say that the issue is specific for Java on MacOSX,
seeing the lack of other users that encounter this problem.

My workaround is a ugly one and it is not really worth doing a pull request
for.

I discovered that when I hover the mousepointer over the year label, the
calendar panel repaints itself and from that moment on looks correct.

In a nutshell, what I did is to extend the
com.github.lgooddatepicker.components.DatePicker.
When the calenderpanel is opened, I look up the Label that is displaying
the year on the calendarpanel in the component hierarchy.
Than some time (100 milliseconds or so) after the calendar panel popup
becomes visible I send a MousEntered event to that Label, and presto the
calendar panel repaints itself correctly.

....
MouseEvent event = new MouseEvent(yearLabel, MouseEvent.MOUSE_ENTERED,
Calendar.getInstance().getTimeInMillis(), 0, 0, 0, 1, false);
yearLabel.dispatchEvent(event);
....

Like said, Its a workaround, not a fix.

Probably in the MacOSX version of the Java virtual machine events and
repaints are executing in a slightly different order which introduces this
erroneous behavior.
I have already seen those things before on occasions.

A potential fix for you could be to generate a MouseEntered event for the
year label after you are done painting the calendarpanel.
But probably it can also be done more cleaner.
In any case you are welcome to my workaround code should you want to have
it. To test any changes you would need to use a Mac though..  :-)


Best regards, Martin











2017-12-11 3:32 GMT+08:00 BlakeTNC <notifications@github.com>:

**Comment by NicholasQu** [comment]
I encountered the same issues in MAC, I just add "this.repaint()" in the method drawCalendar of CalendarPanel， after the loop 

> for (int dateLabelArrayIndex = 0; dateLabelArrayIndex < dateLabels.size(); ++dateLabelArrayIndex) {}

it works for me.
https://github.com/NicholasQu/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/components/CalendarPanel.java

**Comment by BlakeTNC** [comment]
I'm adding a variation of this change to the master branch. I did slightly differently though. I moved the repaint line to be the -last- line of executable code, in the body of the function with the signature:
private void drawCalendar(YearMonth newYearMonth, YearMonth oldYearMonthOrNull)

Please let me know if it still fixes the bug for you in that position. (Ideally, let me know before I build this change into a new release.) Thanks.

**Comment by BlakeTNC** [comment]
I fixed this issue and committed it to the repository. It will also be included in the latest release. Please let me know if it works for you now. Thanks for the bug report.

**Comment by BlakeTNC** [comment]
See the release 10.4.1.
