### ISSUE TITLE
Feature request: DatePanel maximumWidth setting

### ISSUE THREAD

**Issue by godzsa** [LGoodDatePicker/LGoodDatePicker#63]
Add `setSizeDatePanelMaximumWidth(int pixels)` method to `DatePickerSettings`. 

reason: The Default DatePicker is too wide for me, I'd like to adjust it.

**Comment by godzsa** [comment]
Also it would be nice if the height could be set as well

**Comment by BlakeTNC** [comment]
My apologies for the very delayed response. 

In general, I believe the dimensions of the date picker are not handled by the date picker component itself, they are handled by the layout (and parent component) in which the date picker is placed. If it is useful, I might suggest reading the official Java tutorial on layout managers. https://docs.oracle.com/javase/tutorial/uiswing/layout/visual.html

Please let me know if anything else is needed.
