### ISSUE TITLE
DatePicker panel (component) & After Selected date JTextField (Datepicker Component) Background

### ISSUE THREAD

**Issue by MaToxZ** [LGoodDatePicker/LGoodDatePicker#65]
Hi guys,

First at all, I want to thank you and grats you becuase of this amazing lib to solve the issue about a "friendly and nice way to pick a date in JavaSE". This time, I'm developing a personal project which I want to look like material Design, that's why I'm using DatePickerSettings class. I achivied to change all colors on the UI, I even changed the JTextField component background, but my issue comes when:

* I run the program and add 2 DatePickers in a FlowLayout Panel which its background color is "blue", previously, I change the JTextField Background (DatePicker component) to look the same as the panel background, but there is a kind of "Panel" where both JTextField and JButton are embedded when does instance DatePicker Class. this panel has the defaults Java Pane background. I would like to change that background to, so I can get a better apparience.

* After picking a date, the JTextField background (DatePicker Component) changes to white again, could you guide me with any Idea to make this not happen?.

Thank you so much for you support and help, and once again, I'm gratefull with you about this HELPFUL tool.

Attachments:

Pic1
![lgooddatepicker_post_1](https://user-images.githubusercontent.com/4277410/37351996-4688e824-26aa-11e8-98dc-73ef40326b70.jpg)

Pic2
![lgooddatepicker_post_2](https://user-images.githubusercontent.com/4277410/37352016-4faf7af8-26aa-11e8-918c-0fd0f266763c.jpg)

**Comment by BlakeTNC** [comment]
Hello, sorry for the long delay in response.  However, if you still need it, here is the solution. I have also added this example to the full demo class.

        DatePickerSettings dateSettings = new DatePickerSettings();
        datePicker = new DatePicker(dateSettings);
        dateSettings.setColor(DateArea.TextFieldBackgroundValidDate, Color.cyan);

**Comment by BlakeTNC** [comment]
The demo for this functionality is now included in the latest release.  See the release 10.4.1.
