### ISSUE TITLE
Feature request: setters and getters to the datePanels array and background color for CalendarPanel

### ISSUE THREAD

**Issue by BR50Kab** [LGoodDatePicker/LGoodDatePicker#66]
I am trying to use CalendarPanel to add/edit/delete planned holidays (multiple ranged selections). To display the already planned in holidays (recorded in another  List) i would liketo get access to the background color of the datePanesl array and set/get the colors individually. At the moment the list is private and i cant get access?

**Comment by BlakeTNC** [comment]
In the CalendarPanel class,  I do not see a "datePanesl" (or datePanel) array. There is an array list of dateLabels, but that field must remain private. It's possible to specify any background or foreground colors using existing code, specifically through the DateHighlightPolicy and HighlightInformation classes. I'm closing this issue, but please reopen or resubmit if you need to supply more information.
