### ISSUE TITLE
Date picker closes too soon

### ISSUE THREAD

**Issue by cchrisx31** [LGoodDatePicker/LGoodDatePicker#67]
When i open an instance of the date picker and i go to choose the year first, after choosing the year the picker closes and the selection is gone. If i move very fast and as soon as i pick the year i move the mouse to the calendar the picker stays open. I guess it is a focus problem.
The issue exists on Linux Ubuntu 18.04. On Windows 7 it works fine.

**Comment by BlakeTNC** [comment]
hi Chris,
   I've noticed that Linux does sometimes behave differently regarding focus in Java. I personally have little extra time for further upgrades, but I will support submitted fixes. If you have the ability and time to write a fix, please feel free to submit your modifications as a pull request. Any fix for this topic should be tested on Windows and Linux before submitting.

Warm regards,
-BlakeTNC
