### ISSUE TITLE
setDefaultYearMonth(YearMonth) is undefined for the type DatePickerSettings

### ISSUE THREAD

**Issue by Cliff2310** [LGoodDatePicker/LGoodDatePicker#68]
First, good package, thank you.
I am using LGoodDatePicker to select the start and stop date/time for some data processing.
I use **.setDateRangeLimits(startDate, stopDate);** to set the limits.  It works just fine,  except the caldendar opens to the current date. OK I found 'setDefaultYearMonth' but Eclipse says 
"**The method setDefaultYearMonth(YearMonth) is undefined for the type DatePickerSettings**"?
I see the method in the source code.  I have the jar 'LGoodDatePicker-10.3.1-java' 
If you need any more information, let me know.
Cliff

**Comment by Cliff2310** [comment]
I extracted the LgoodDatePicker-10.3.1-java.jar file and ran javap on these class files
under  components:
DatePickerSettings
DatePickerSettings$DateArea
DatePickerSettings$1
I piped the out put to text (.txt) files and searched for “setDefaultYearMonth”.
DatePickerSettings → Not Found
DatePickerSettings$DateArea → Not Found
DatePickerSettings$1  → Not Found
I would believe that the compile was made with the old source.

**Comment by Cliff2310** [comment]
I do not know how I closed this.

**Comment by BlakeTNC** [comment]
I think you are right. I will have to find the problem, recompile, and re-release to fix it.

**Comment by BlakeTNC** [comment]
I fixed this issue and committed it to the repository. It will also be included in the latest release. Please let me know if it works for you now. Thanks for the bug report.

**Comment by BlakeTNC** [comment]
Correction: The function setDefaultYearMonth() was added in June 2017, but I have not created any new releases since then. That explains why it was not in that older release file. I'm building a new release now.
