### ISSUE TITLE
DatePicker calendar popup still opens even when it is disabled.

### ISSUE THREAD

**Issue by ngcabang** [LGoodDatePicker/LGoodDatePicker#70]
@BlakeTNC can you please check this, the DatePicker calendar popup still opens even set with 

``datePicker.setEnabled(false);``

I think you need to make a conditional here if the datepicker is currently enabled.

https://github.com/LGoodDatePicker/LGoodDatePicker/blob/a93d25ae0c805930a90c4ae6705c7984e3dd5dc2/Project/src/main/java/com/github/lgooddatepicker/components/DatePicker.java#L796

Thanks.

**Comment by BlakeTNC** [comment]
I'll need to duplicate this. Can you send minimal example code that demonstrates the behavior? (You could modify the BasicDemo class if it makes the example easier.)

**Comment by BlakeTNC** [comment]
Please reopen or resubmit this issue if you are able to provide example code.
