### ISSUE TITLE
Use EnumMap for DatePickerSettings.colors

### ISSUE THREAD

**Issue by SirIntellegence** [LGoodDatePicker/LGoodDatePicker#71]
It is a smidge of a nit pick, but it is recommended to use an EnumMap when the Map Key type is an enum. Consider this a very low priority.

**Comment by SirIntellegence** [comment]
@felixtfl, You should file that as a separate bug/feature request since I am not the maintainer of this library.

**Comment by felixtfl** [comment]
>
> 
> @felixtfl, You should file that as a separate bug/feature request since I am not the maintainer of this library.

sorry about that.

**Comment by WiseEagleOwl** [comment]
@SirIntellegence
This issue should be solved with the merge of your PR #72.
Feel free to leave a comment if this hasn't solved the issue for you.
