### ISSUE TITLE
LGoodDatePicker 10.4.1 is not on maven ?

### ISSUE THREAD

**Issue by martinm1000** [LGoodDatePicker/LGoodDatePicker#73]
Hi, Looks like the last release didn't make it to maven ?

**Comment by bojorquezja** [comment]
It has issues, they fix them in master but didn´t publish the new version.

**Comment by WiseEagleOwl** [comment]
@martinm1000 @kevinbbd @MicMun @qmjy @bojorquezja
*LGoodDatePicker* `v11.0.0` was just released to the Maven Central Repository (it can take some time until the mirroring process is finished).
The publishing to the Maven Central Repository was a manual process that was just now replaced with an automatic one. Future releases will hopefully reach the maven repository in a more timely manner.
