### ISSUE TITLE
TimeChangeEvent: getNewTime returns 00:00

### ISSUE THREAD

**Issue by TheCardinalSystem** [LGoodDatePicker/LGoodDatePicker#75]
I added a `TimeChangeListener` to my `TimePicker`. When I select a time on the GUI, the event is tired successfully. However, when I select `12:00am`, the event fires with `TimeChangeEvent#getNewTime()` returning `00:00`. I ran this through my debugger, but I cannot find the source of the issue. I'm using LGoodDatePicker 10.4.1. My `DateTimePicker` is constructed as follows:
```Java
		dateSettings = new DatePickerSettings();
		timeSettings = new TimePickerSettings();
		dateSettings.setAllowEmptyDates(false);
		timeSettings.setAllowEmptyTimes(false);
		dateTimePicker = new DateTimePicker(dateSettings, timeSettings);
		dateTimePicker.getTimePicker().addTimeChangeListener(this);
```
The listener looks like this:
```Java
	@Override
	public void timeChanged(TimeChangeEvent event) {
		hour.setText(HourUtils.getHour(event.getNewTime()).toString(WebLang.LAT));
	}
```
It's all very basic. I'm not sure where the error is occurring. The `TimePicker` component updates properly when I select `12:00am` - it's only the even that is messed up.

**Comment by BlakeTNC** [comment]
Hello,
This is the correct behavior, because the LocalTime class operates internally on a 24-hour format, not a 12 hour format. The time you are setting, 12 AM, is the same as LocalTime.MIN, which is 00:00. By contrast, LocalTime.MAX is '23:59:59.999999999'. Put another way, the value 00:00 represents the first instant of the day on a 24-hour clock. See also: https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html

Warm regards,
BlakeTNC

**Comment by TheCardinalSystem** [comment]
> Hello,
> This is the correct behavior, because the LocalTime class operates internally on a 24-hour format, not a 12 hour format. The time you are setting, 12 AM, is the same as LocalTime.MIN, which is 00:00. By contrast, LocalTime.MAX is '23:59:59.999999999'. Put another way, the value 00:00 represents the first instant of the day on a 24-hour clock. See also: https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html
> 
> Warm regards,
> BlakeTNC

You know, I am very much embarrassed by this. I've been programming in Java for 4 years now and I made such a simple mistake. Thank you for your patients :)
