### ISSUE TITLE
Can i show just actual month on Calendar and disable navigation on it?

### ISSUE THREAD

**Issue by Serranosoft** [LGoodDatePicker/LGoodDatePicker#79]
Im trying to paint some dates using 
`if (
date.getDayOfMonth() == tareas.getResultados_tareas().get(i).getFecha_realizar().toLocalDate().getDayOfMonth()) { 
                    return new HighlightInformation(Color.CYAN, null, "null");
                }` 

but that highlight all those days on all month and i dont know how can i distinguish days and month so i think it is more easy to just disable navigation and just show days of actual month there is any setting to do it? thanks

**Comment by WiseEagleOwl** [comment]
You can always use `date.getMonthValue()` to access the month as an integer value in range 1 to 12 and compare it with the current month to limit your highlighting to the current month.

As the `DatePickerSettings` already allow you to limit the date range which is accepted I don’t think it would be a useful feature to disable navigation on the *DatePicker* as it would be less granular and redundant.
To set a date range you can use `dateSettings.setDateRangeLimits(startDate, endDate)`

Feel free to leave a comment if this hasn't solved the issue for you.
