### ISSUE TITLE
Feature request: Handle setEnabled

### ISSUE THREAD

**Issue by mickdermack** [LGoodDatePicker/LGoodDatePicker#8]
The pickers continue to function normally after calling .setEnabled(false), although I expected them to appear greyed out and not react to user input.

**Comment by BlakeTNC** [comment]
Hello mickdermack, 

  Both of the pickers extend the JPanel class, so if you call setEnabled(false), you are only disabling the panel that the picker is sitting in. All settings on the pickers are set through the DatePickerSettings or TimePickerSettings classes.

Here is an example of how you disable a picker. A version of this code, and other examples, exist in the demo application.

        // Create a date picker: Disallow keyboard editing.
        DatePickerSettings settings = new DatePickerSettings();
        settings.allowKeyboardEditing = false;
        DatePicker datePicker = new DatePicker(dateSettings);

warm regards,
Blake

**Comment by BlakeTNC** [comment]
Actually, it occurs to me that you might want more than disabling the keyboard input... Do you also wish and to disable mouse input at the same time? Normally, the set enabled function disables -all- input for a component, and basically freezes any text that has already been entered.

**Comment by mickdermack** [comment]
Yes, I wanted a way to disable all input (keyboard, mouse, whatever else) to the chooser and make it appear greyed out while keeping the current values. Just like (for example) a combo box, after calling setEnabled(false) on it.

**Comment by BlakeTNC** [comment]
Hello, this feature has been implemented for the date picker and time picker. See the release of [LGoodDatePicker 4.1.4](https://github.com/LGoodDatePicker/LGoodDatePicker/releases). I still plan to add it to the DateTimePicker. 

Warm regards,
Blake

**Comment by mickdermack** [comment]
Awesome, thanks!
Am 11.03.2016 04:21 schrieb "BlakeTNC" <notifications@github.com>:

**Comment by BlakeTNC** [comment]
The feature request is completed. This feature is now added to all components, with the release of [LGoodDatePicker 4.1.5](https://github.com/LGoodDatePicker/LGoodDatePicker/releases).
