### ISSUE TITLE
Cant start my project with binded jar file

### ISSUE THREAD

**Issue by ghost** [LGoodDatePicker/LGoodDatePicker#85]
Helo,

I've got a question.

When I start my project in Eclipse I get this on console:

Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for LGoodDatePicker-10.4.1.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class org.jdesktop.swingbinding.adapters.AbstractButtonAdapterProvider not in module

What is missing? 

Thank you.

**Comment by WiseEagleOwl** [comment]
*LGoodDatePicker* has a dependency on `org.jdesktop.beansbinding` version 1.2.1. The `org.jdesktop.swingbinding` package is part of this dependency.
Eclipse seems to encounter an issue while loading that dependency.

The only reason for that dependency seems to be the *DataBindingDemo*: https://github.com/LGoodDatePicker/LGoodDatePicker/blob/5876ae38703512d6e6eb1507cbbd7ef88555185d/Project/src/main/java/com/github/lgooddatepicker/demo/zExtra_DataBindingDemo.java#L41 All content of that file is already commented out, so the dependency can be completely avoided by building LGoodDatePicker yourself and removing the dependency from the `pom.xml` file:
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/5876ae38703512d6e6eb1507cbbd7ef88555185d/Project/pom.xml#L82-L87

@BlakeTNC 
Is there any other reason, that I have missed, why *LGoodDatePicker* needs this dependency?  If that's not the case I could create a PR commenting out the *beansbinding* dependency from the `pom.xml` to avoid any further issues regarding this dependency.
