### ISSUE TITLE
Runtime Exception in Mouse Event

### ISSUE THREAD

**Issue by anduril92** [LGoodDatePicker/LGoodDatePicker#87]
Hello
I have used this classes for my personal project. I have created a graphic interface with a Calendar Panel and a Time Picker. I would create an application which permit to select a date from Calendar Panel and to select a time from Time Picker. Inizially, Calendar Panel is visible while Time Picker is not visible. Once selected a date from Calendar Panel, I handle the event and enable the Time Picker, so as to make visible it. But, once selected a hour from Time Picker appears the exception " java.lang.RuntimeException: TimeMenuPanel.mouseReleasedWhileTimeListIsOpen() Time menu list index is out of bounds. This should not happen.". Sorry for my English.
best regards and see you soon

**Comment by WiseEagleOwl** [comment]
Hello @anduril92 
Thank you for taking the time to report an issue. As a side note: I would not recommend posting your personal email publicly on the internet. You can use the triple dot button (...) to select *Edit* and change your issue and remove your email address. You will still automatically receive emails if somebody responds to the issue you opened.
The problem you are describing seems to occur under very specific circumstances. 
If you could provide a short and concise test case that reproduces the issue, then I might be able to fix it. 
If you take a look at the existing tests in:
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/5876ae38703512d6e6eb1507cbbd7ef88555185d/Project/src/test/java/TestGithubIssues.java#L47-L48
You will find a short test which reproduces issue #82 where an exception is thrown when closing the window while the date picker popup is still open.
You could write a short code example similar to that test case using `java.awt.Robot` to simulate the mouse click causing the exception in your case. I guess it would look something like this:
```Java
TimePicker time_picker = new TimePicker();
JFrame testWin = new JFrame();
testWin.add(time_picker);
testWin.pack();
testWin.setVisible(true);
Thread.sleep(10);
//... recreate your exact situation here, setting the time picker settings
//... opening the time picker popup etc.
Robot robot = new Robot();
robot.mouseMove(XXX, YYY); //move to the click position where the error occurs
Thread.sleep(10);
// click the mouse
robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
Thread.sleep(10);
robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
// the exception should now be thrown from mouseReleasedWhileTimeListIsOpen()
```

**Comment by anduril92** [comment]
So to solve the problem I have to use a Thread.sleep (10) to give TimePicker a time to make it disappear from the dropdown list.

**Comment by WiseEagleOwl** [comment]
@anduril92 
> to solve the problem I have to use a Thread.sleep (10) to give TimePicker a time to make it disappear from the dropdown list.

Does that mean, you have found a solution to your issue, that does not require modifications to the *DataPicker* component itself?

**Comment by anduril92** [comment]
No. I wrote wrong. It was a question. However, I solved the problem by inserting a JButton as a further request to confirm the selection date. In this way, TimePicker has a time to disappear and not it throw the exception.

**Comment by WiseEagleOwl** [comment]
Great to hear you have found a workaround for this issue.

If you want you can still post a short code sample reproducing the issue as explained [above](https://github.com/LGoodDatePicker/LGoodDatePicker/issues/87#issuecomment-602047418). This would help me to reproduce the problem and hopefully fix it, so that *LGoodDatePicker* works more reliable in the future.
